### ISSUE TITLE
Add support for per-subdivision trophies and medals

### ISSUE THREAD

**Issue by smayya337** [Duosmium/sciolyff-ruby#1]
Some competitions (e.g. Rustin 2021) are doing different numbers of medals/trophies for different subdivisions. However, `sciolyff` has `medals` and `trophies` as parameters of the `Tournament` class (see [here](https://github.com/Duosmium/sciolyff/blob/master/lib/sciolyff/interpreter/tournament.rb#L112)). Some way of adding `medals` and `trophies` fields that supersede the ones in `Tournament` would be good to have. `start date` and `end date` might be worth viewing as an example of a similar feature, though it's worth noting that those were all in the same class, and that doing this sort of thing between classes is likely more complicated.

**Comment by alchzh** [comment]
Doesn't this already exist?

**Comment by smayya337** [comment]
@alchzh nope, the only way to set them is at the `Tournament` level (see [`tournament.rb`](https://github.com/Duosmium/sciolyff/blob/master/lib/sciolyff/interpreter/tournament.rb) and [`tracks.rb`](https://github.com/Duosmium/sciolyff/blob/master/lib/sciolyff/interpreter/tracks.rb)).
